use publishing
DROP TABLE IF EXISTS PUBLISHING_BOOKS_WITH_AUTHORS
CREATE TABLE PUBLISHING_BOOKS_WITH_AUTHORS (isbn varchar(20), title varchar(256), author varchar(256))
CREATE INDEX PUBLISHING_BOOKS_WITH_AUTHORS_ISBN ON PUBLISHING_BOOKS_WITH_AUTHORS(isbn)
CREATE INDEX PUBLISHING_BOOKS_WITH_AUTHORS_TITLE ON PUBLISHING_BOOKS_WITH_AUTHORS(title)
CREATE INDEX PUBLISHING_BOOKS_WITH_AUTHORS_AUTHOR ON PUBLISHING_BOOKS_WITH_AUTHORS(author)