drop table if exists BOOKS_AUTHORS;
drop table if exists BOOKS;
drop table if exists PUBLISHERS;
drop table if exists AUTHORS;
create table BOOKS (ID int AUTO_INCREMENT, PUBLISHER_NAME varchar(100) NOT NULL, ISBN VARCHAR(20), TITLE VARCHAR(256), PRICE FLOAT, AUTHOR_LASTNAME varchar(100), AUTHOR_FIRSTNAME varchar(100), primary key (ID));
INSERT INTO BOOKS (ISBN, TITLE, PRICE, AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, PUBLISHER_NAME) VALUES ('ISBN1', 'Title1', 19.99, 'Meier', 'Hans', 'Springer');
INSERT INTO BOOKS (ISBN, TITLE, PRICE, AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, PUBLISHER_NAME) VALUES ('ISBN1', 'Title1', 19.99, 'Schneider', 'Hanna', 'Springer');
INSERT INTO BOOKS (PUBLISHER_NAME) VALUES ('Addison');
SELECT PUBLISHER_NAME FROM BOOKS;
SELECT DISTINCT PUBLISHER_NAME FROM BOOKS;
SELECT * FROM BOOKS;
SELECT AUTHOR_LASTNAME, AUTHOR_FIRSTNAME FROM BOOKS;
SELECT ISBN, TITLE, PRICE FROM BOOKS WHERE PUBLISHER_NAME='Springer'
