select BOOKS.ISBN, BOOKS.TITLE from BOOKS JOIN PUBLISHERS ON PUBLISHERS.ID = BOOKS.PUBLISHER_ID where PUBLISHERS.NAME = 'Springer';
select AUTHORS.LASTNAME, AUTHORS.FIRSTNAME, PUBLISHERS.NAME FROM AUTHORS JOIN BOOKS_AUTHORS ON BOOKS_AUTHORS.AUTHOR_ID = AUTHORS.ID JOIN PUBLISHERS ON PUBLISHERS.ID = BOOKS_AUTHORS.BOOK_ID WHERE AUTHORS.LASTNAME = 'Schneider';
