drop table if exists BOOKS_AUTHORS;
drop table if exists BOOKS;
drop table if exists PUBLISHERS;
drop table if exists AUTHORS;

create table PUBLISHERS (ID int AUTO_INCREMENT, NAME VARCHAR(100) UNIQUE NOT NULL, primary key (ID));
create table BOOKS (ID int AUTO_INCREMENT, PUBLISHER_ID int NOT NULL, ISBN VARCHAR(20) UNIQUE NOT NULL, TITLE VARCHAR(256) NOT NULL , Constraint TITLE_MIN_3_CHARS CHECK (LENGTH(TITLE) >= 0), PRICE FLOAT Constraint PRICE_GREATER_THAN_0 CHECK (PRICE >= 0), primary key (ID), FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(ID));
create table AUTHORS (ID int AUTO_INCREMENT, FIRSTNAME varchar(100) NOT NULL, LASTNAME varchar(100) NOT NULL, primary key (id));
create table BOOKS_AUTHORS (BOOK_ID int not null, AUTHOR_ID int not null, primary key (BOOK_ID, AUTHOR_ID), foreign key (AUTHOR_ID) references AUTHORS (ID), foreign key (BOOK_ID) references BOOKS (ID));

INSERT INTO PUBLISHERS (NAME) VALUES('Springer');
INSERT INTO PUBLISHERS (NAME) VALUES('Addison');
INSERT INTO BOOKS (ISBN, TITLE, PRICE, PUBLISHER_ID) VALUES ('ISBN1', 'Title1', 19.99, (SELECT ID FROM PUBLISHERS WHERE NAME='Springer'));
INSERT INTO AUTHORS (LASTNAME, FIRSTNAME) VALUES('Meier', 'Hans');
INSERT INTO AUTHORS (LASTNAME, FIRSTNAME) VALUES('Schneider', 'Hanna');
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES(1, 1);#schlampig, hier müssten die IDs selektiert werden
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES(1, 2);#für den Test hier aber OK
#INSERT INTO BOOKS (ISBN, TITLE, PRICE) VALUES ('ISBN2', 'Title2', 9.99);#Geht nicht, NOT NULL
#INSERT INTO BOOKS (ISBN, TITLE, PRICE, PUBLISHER_ID) VALUES ('ISBN2', 'Title2', 9.99, 42); #Geht nicht: Foreign Key
#INSERT INTO BOOKS (ISBN, TITLE, PRICE, PUBLISHER_ID) VALUES ('ISBN2', 'Title2', -9.99, 1); #Price Constraint violation
