SELECT * FROM PUBLISHING_AUTHORS;
SELECT COUNT(*) FROM PUBLISHING_BOOKS WHERE PRICE > 200;
SELECT SUM(b.PRICE) FROM PUBLISHING_BOOKS as b JOIN PUBLISHING_PUBLISHERS as p ON b.publisher_publisherId = p.publisherId where p.publisherName='Publisher1';
SELECT SUM(b.PRICE) FROM PUBLISHING_BOOKS as b JOIN PUBLISHING_BOOKS_AUTHOR as ba ON ba.books_id = b.id JOIN PUBLISHING_AUTHORS as a ON ba.authors_authorId=a.authorId  where a.lastname='AuthorLastname1';
SELECT ba.books_id FROM PUBLISHING_BOOKS_AUTHOR as ba GROUP BY ba.books_id;
SELECT COUNT(*) FROM PUBLISHING_BOOKS as b JOIN PUBLISHING_BOOKS_STATISTICS as bs ON b.id = bs.id JOIN PUBLISHING_STATISTICS as s ON s.id = bs.BOOK_STATISTICS_ID WHERE s.sold > 500;
SELECT b.TITLE, k.KEYWORDS FROM PUBLISHING_BOOKS as b JOIN PUBLISHING_BOOK_KEYWORDS as k ON b.id = k.Book_id;
