drop table if exists BOOKS_AUTHORS;
drop table if exists BOOKS;
drop table if exists PUBLISHERS;
drop table if exists AUTHORS;
create table PUBLISHERS (ID int AUTO_INCREMENT, NAME VARCHAR(100), primary key (ID));
create table BOOKS (ID int AUTO_INCREMENT, PUBLISHER_ID int NOT NULL, ISBN VARCHAR(20), TITLE VARCHAR(256), PRICE FLOAT, AUTHOR_LASTNAME varchar(100), AUTHOR_FIRSTNAME varchar(100), primary key (ID), FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(ID));
INSERT INTO PUBLISHERS (NAME) VALUES('Springer');
INSERT INTO PUBLISHERS (NAME) VALUES('Addison');
INSERT INTO BOOKS (ISBN, TITLE, PRICE, PUBLISHER_ID, AUTHOR_LASTNAME, AUTHOR_FIRSTNAME) VALUES ('ISBN1', 'Title1', 19.99, (SELECT ID FROM PUBLISHERS WHERE NAME='Springer'), 'Meier', 'Hans');
INSERT INTO BOOKS (ISBN, TITLE, PRICE, PUBLISHER_ID, AUTHOR_LASTNAME, AUTHOR_FIRSTNAME) VALUES ('ISBN1', 'Title1', 19.99, (SELECT ID FROM PUBLISHERS WHERE NAME='Springer'), 'Schneider', 'Hanna');
SELECT * FROM PUBLISHERS;
SELECT * FROM BOOKS;
SELECT b.ISBN, b.LASTNAME from BOOKS
