alter table PUBLISHING_BOOK_KEYWORDS drop foreign key FKt5v5fei0iq1j7gnw4rksqp2yn;
alter table PUBLISHING_BOOKS drop foreign key FK3fkhfh001c0t5r9tyg48qguth;
alter table PUBLISHING_BOOKS_AUTHOR drop foreign key FKl2b27u8bdnptnf4pmo86qe4cl;
alter table PUBLISHING_BOOKS_AUTHOR drop foreign key FK1c7d3t7x75n12pb8awaqydwe8;
alter table PUBLISHING_BOOKS_STATISTICS drop foreign key FKofw7i2cd4rj7s5n09gvgck8ov;
alter table PUBLISHING_BOOKS_STATISTICS drop foreign key FKq8rs4ou51h09tqg7w567412pt;
alter table PUBLISHING_POEMS drop foreign key FK1re9xbvd29ej5h8gnek73v8xm;
alter table PUBLISHING_SCHOOLBOOK drop foreign key FKhhemg4orngnvk5ijuw040k4cl;
alter table PUBLISHING_SPECIALISTBOOK drop foreign key FKm3s1por74rklnnc7hw55ynfby;
drop table if exists hibernate_sequence;
drop table if exists PUBLISHING_AUTHORS;
drop table if exists PUBLISHING_BOOK_KEYWORDS;
drop table if exists PUBLISHING_BOOKS;
drop table if exists PUBLISHING_BOOKS_AUTHOR;
drop table if exists PUBLISHING_BOOKS_STATISTICS;
drop table if exists PUBLISHING_POEMS;
drop table if exists PUBLISHING_PUBLISHERS;
drop table if exists PUBLISHING_SCHOOLBOOK;
drop table if exists PUBLISHING_SPECIALISTBOOK;
drop table if exists PUBLISHING_STATISTICS;

